# Structural drift-guard: every name listed in `.SPEC_GROUPS` (R/utils.R) must
# correspond to an actual field in `default_specs()`, and every field in
# `default_specs()` must belong to exactly one group.
#
# Background: `.SPEC_GROUPS` drives `print_specs()` and the introspection
# tables generated by `vignettes/parameter-reference.Rmd` (via
# `.param_table()`). The docstring of `.SPEC_GROUPS` notes that absent names
# are silently skipped — a deliberate forward-compat hatch that turned into a
# source of drift: by the time of Phase A item 1 (2026-05-16), 13 names in
# `.SPEC_GROUPS` no longer existed in `default_specs()`
# (`max_agents_per_cell`, `signal_mutation_sd`, `carrion_decay`,
# `verbose_julia`, ...), pollluting the introspection surface and the
# vignette tables without producing a visible error.
#
# `test-spec-wiring.R` catches the *Julia* side (every R field must have a
# Julia consumer). This test catches the *R* side (every grouping must point
# at a real R field, and every R field must be grouped).

library(testthat)

test_that("every .SPEC_GROUPS entry exists in default_specs() (no ghost names)", {
  s      <- default_specs()
  g      <- unlist(clade:::.SPEC_GROUPS, use.names = FALSE)
  ghosts <- setdiff(g, names(s))
  expect_equal(
    ghosts, character(0L),
    info = paste(
      "Found names in `.SPEC_GROUPS` that do not exist in `default_specs()`.",
      "Either (a) restore the field to `default_specs()`, (b) remove the",
      "name from `.SPEC_GROUPS` (R/utils.R), or (c) confirm the field is",
      "intentionally reserved-for-future and document that next to the",
      "grouping.\nGhost names:", paste(ghosts, collapse = ", ")
    )
  )
})

test_that("every default_specs() field appears in some .SPEC_GROUPS entry", {
  s       <- default_specs()
  g       <- unlist(clade:::.SPEC_GROUPS, use.names = FALSE)
  orphans <- setdiff(names(s), g)
  expect_equal(
    orphans, character(0L),
    info = paste(
      "Found fields in `default_specs()` that are not listed in any",
      "`.SPEC_GROUPS` group (R/utils.R::.SPEC_GROUPS). When you add a new",
      "field to `default_specs()`, also add its name to the appropriate",
      "group so `print_specs()` and `parameter-reference.Rmd` pick it up.\n",
      "Orphan fields:", paste(orphans, collapse = ", ")
    )
  )
})
